/** @typedef {Record<string, unknown>} RcAdvanceRawResponse */

/** Scalar keys on `result` (excluding nested objects). */
export const RESULT_SCALAR_KEYS = [
  'state_code',
  'state',
  'office_code',
  'office_name',
  'reg_no',
  'reg_date',
  'purchase_date',
  'owner_count',
  'owner_name',
  'owner_father_name',
  'current_address_line1',
  'current_address_line2',
  'current_address_line3',
  'current_district_name',
  'current_state',
  'current_state_name',
  'current_pincode',
  'current_full_address',
  'permanent_address_line1',
  'permanent_address_line2',
  'permanent_address_line3',
  'permanent_district_name',
  'permanent_state',
  'permanent_state_name',
  'permanent_pincode',
  'permanent_full_address',
  'owner_code_descr',
  'reg_type_descr',
  'vehicle_class_desc',
  'chassis_no',
  'engine_no',
  'vehicle_manufacturer_name',
  'model_code',
  'model',
  'body_type',
  'cylinders_no',
  'vehicle_hp',
  'vehicle_seat_capacity',
  'vehicle_standing_capacity',
  'vehicle_sleeper_capacity',
  'unladen_weight',
  'vehicle_gross_weight',
  'vehicle_gross_comb_weight',
  'fuel_descr',
  'color',
  'manufacturing_mon',
  'manufacturing_yr',
  'norms_descr',
  'wheelbase',
  'cubic_cap',
  'floor_area',
  'ac_fitted',
  'audio_fitted',
  'video_fitted',
  'vehicle_catg',
  'dealer_code',
  'dealer_name',
  'dealer_address_line1',
  'dealer_address_line2',
  'dealer_address_line3',
  'dealer_district',
  'dealer_pincode',
  'dealer_full_address',
  'sale_amount',
  'length',
  'width',
  'height',
  'reg_upto',
  'fit_upto',
  'tax_upto',
  'annual_income',
  'imported_vehicle',
  'status',
  'vehicle_type',
  'tax_mode',
  'mobile_no',
  'email_id',
  'pan_no',
  'aadhar_no',
  'passport_no',
  'ration_card_no',
  'voter_id',
  'dl_no',
];

/** Nested object on `result` → flat key prefix. */
export const RESULT_NESTED_PREFIXES = {
  vehicle_insurance_details: 'insurance_',
  vehicle_pucc_details: 'pucc_',
  financer_details: 'financer_',
  permit_details: 'permit_',
  latest_tax_details: 'tax_',
};

export const TOP_LEVEL_FLAT_KEYS = [
  'status_code',
  'status',
  'message',
  'txn_id',
  'response_type',
  'billable',
];

/** Flat key used for result.status (avoids clash with top-level status). */
export const RESULT_STATUS_FLAT_KEY = 'vehicle_status';

export const RC_ADVANCE_FETCH_TTL_MS = 7 * 24 * 60 * 60 * 1000;

export const DEFAULT_RC_ADVANCE_MOCK_FILE = 'docs/rc_advance_mock_by_vrn.json';
