{{- if .Values.pdb.enabled }}
{{- if .Values.apiExpress.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vahanplus.fullname" . }}-api-express
  labels:
    {{- include "vahanplus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-express
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api-express
      app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}
{{- if .Values.web.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vahanplus.fullname" . }}-web
  labels:
    {{- include "vahanplus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
